### PR TITLE
[Feature] Add working directory option to FileSystems

### LINKED ISSUE #500: [Feature][Storage] Add working directory support
### Already searched before asking?

- [X] I had searched in the [feature](https://github.com/flowerfine/scaleph/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Usage Scenario

Now the storage module does not support working directory. If `local` mode was chosen, all files will store in the project root directory, It's bad.
So we should allow user to set the working directory.

### Description

 Add `workingDirectory` option to the application properties file. User can change working directory by modify this option.

### Are you willing to submit a PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

### PR DESCRIPTION
**Pull request by LiuBodong**
## Purpose of this pull request
Finish this ISSUE #500

## Brief change log
Add working directory support

Closes #500

### CODE REVIEW

**Comment by kalencaya** [comment]
scaleph has defined a work directory for internal use on `scaleph-system` module's `cn.sliew.scaleph.system.util.SystemUtil` class previously,  can you combine them together?

**Comment by LiuBodong** [comment]
> scaleph has defined a work directory for internal use on `scaleph-system` module's `cn.sliew.scaleph.system.util.SystemUtil` class previously, can you combine them together?

The working directory in `cn.sliew.scaleph.system.util.SystemUtil`  defines where the remote file `downloads` to local. But the `workingDirectory` in `file-system` scope defines where the file should `upload` to remote. They should not combine together.

**Comment by kalencaya** [comment]
Of course they have two different purposes, one for internal download and one for hdfs on local filesystem, but the two directory are all used by scaleph self and we should combine them within the same workspace such as `$workspace/download` or `$workspace/upload`, not `$workspace-1/download` or `$worksapce-2/upload`

**Comment by LiuBodong** [comment]
> Of course they have two different purposes, one for internal download and one for hdfs on local filesystem, but the two directory are all used by scaleph self and we should combine them within the same workspace such as `$workspace/download` or `$workspace/upload`, not `$workspace-1/download` or `$worksapce-2/upload`

I'm trying to understand what you said...

we should define an option named workspace, both the local and remote filesystem use this option as the workspace. For example, if we set the workspace to `/scaleph/workspace`, we create random workspace and download files to `LOCAL Directory` in `file:///scaleph/workspace`. On the other hand, we upload the resources to remote filesystem in `hdfs:///scaleph/workspace` of HDFS or `s3a:///scaleph/workspace` of S3 or `file:///scaleph/workspace` of local.

Is this right?

**Comment by kalencaya** [comment]
Firstly for hdfs on local FileSystem,  default working directory is root path, which is not good. But for other FileSystem implementions such as S3 or OSS, they are just ok.

Secondly scaleph needs FileSystem resource for internal use on host machine, which can be called as `workspace` or something else. scaleph already defined it on `SystemUtil`, then scaleph can download remote file to this directory or unzip compressed files, where everything needing local FileSystem can be operated there.

Specifying hdfs lcoal working directory is similiar with download or unzip files, they all should be in the same `workspace` on host machine, define two directory on host machine is improperly

**Review by kalencaya — APPROVED** [review]

**Comment by kalencaya** [comment]
+1

**Pull request merged**
