### PR TITLE
[feature] Add flink-sql-template module

### LINKED ISSUE #530: [Feature][scaleph-sql-template] add flink sql template jar and flink sql image
### Already searched before asking?

- [X] I had searched in the [feature](https://github.com/flowerfine/scaleph/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Usage Scenario

There are two ways for submitting flink sql job, one is template jar such as [sql-runner](https://github.com/apache/flink-kubernetes-operator/blob/release-1.5/examples/flink-sql-runner-example/src/main/java/org/apache/flink/examples/SqlRunner.java), other is sql gateway which submits JobGraph directly.
Template jar is an easily way to support flink sql job and scaleph wants to implement this firstly.

### Description

There are two tasks or stages:

- [ ] add a `scaleph-engine`/`scaleph-sql-template` module and implement the template main class such as [sql-runner](https://github.com/apache/flink-kubernetes-operator/blob/release-1.5/examples/flink-sql-runner-example/src/main/java/org/apache/flink/examples/SqlRunner.java).
- [ ] add template sql docker image which names `scaleph/scaleph-sql-template-${flinkversion}-${jdkversion}` such as [Dockerfile](https://github.com/apache/flink-kubernetes-operator/blob/release-1.5/examples/flink-sql-runner-example/Dockerfile).

### Are you willing to submit a PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

### PR DESCRIPTION
**Pull request by LiuBodong**
## Purpose of this pull request
This pr solves #530 
close #530

### CODE REVIEW

**Comment by kalencaya** [comment]
Can you add workflow steps building flink sql template image automatically to `docker-build.yml`, `docker-release.yml` and `release.yml`?

**Comment by LiuBodong** [comment]
> Can you add workflow steps building flink sql template image automatically to `docker-build.yml`, `docker-release.yml` and `release.yml`?

OK

**Comment by LiuBodong** [comment]
Added git flow configuration for auto building

**Review by kalencaya — APPROVED** [review]

**Comment by kalencaya** [comment]
+1

**Pull request merged**
